
<div style='background:linear-gradient(135deg,#0f172a,#1e293b 45%,#334155);padding:32px 0px;border-radius:18px;color:white;text-align:center;box-shadow:0 18px 40px rgba(15,23,42,0.28);'>
  <h1 style='margin:0;font-size:2.3rem;letter-spacing:0.04em;'>NumPy Part-1 Master Notebook</h1>
  <p style='margin:12px 0 0;font-size:1.05rem;opacity:0.92;'>Random numbers, ndarray operations, copying, indexing, and iteration</p>
  <p style='margin:10px 0 0;font-size:0.95rem;opacity:0.8;'>Prepared by Salek Masud Parvez</p>
</div>

## 🚀 1. NumPy Introduction

In [2]:
import numpy as np

numpy_array = np.array([1,2,3,4,4])
print(type(numpy_array))

<class 'numpy.ndarray'>


## 🚀 2. NumPy vs Python List (Important Concept)

In [ ]:
num_list = [1, 2, 3, 4]
num_array = np.array([1, 2, 3, 4])

print("List * 5 =>", num_list * 5)
print("Array * 5 =>", num_array * 5)

## 🧠 3. NumPy Type Upcasting (VERY IMPORTANT)

In [68]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("int array:", arr_1d.dtype)

# 🔼 Upcasting: int -> float
arr_1d1 = np.array([1, 2, 3, 4, 5.9])
print("int + float =>", arr_1d1.dtype)

# 🔼 Upcasting: number -> string
arr_1d2 = np.array([1, 2, 3, 4, "5"])
print("int + string =>", arr_1d2.dtype)

# 🔼 Manual dtype control
arr_1d3 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print("forced int8 =>", arr_1d3.dtype)

# 🔼 advance dtype control
arr_1d4 = np.array([121,222,11])
arr_1d4.astype(np.int16)
print("outside forced int16 =>", arr_1d4.dtype)


int array: int64
int + float => float64
int + string => <U21
forced int8 => int8
outside forced int16 => int64


## 📊 4. Array Properties (Shape, Dim, Type, Size)

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)
print("shape:", arr.shape)
print("dim:", arr.ndim)
print("dtype:", arr.dtype)
print("size:", arr.size)

[1 2 3 4 5]
shape: (5,)
dim: 1
dtype: int64
size: 5


## 📊 4.1. Array Properties (Size advance)

In [66]:
# =====================================================
# NumPy size() and axis Understanding (1D, 2D, 3D)
# =====================================================

import numpy as np

# =====================================================
# 1D ARRAY
# =====================================================
print("\n========== 1D ARRAY ==========")

arr_1d = np.array([10, 20, 30, 40, 50])

print("Array:", arr_1d)

# Total elements
print("np.size(arr_1d):", np.size(arr_1d))  

# Axis concept in 1D
print("np.size(arr_1d, axis=0):", np.size(arr_1d, axis=0))

# =====================================================
# 2D ARRAY
# =====================================================
print("\n========== 2D ARRAY ==========")

arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Array:\n", arr_2d)

# Total elements
print("np.size(arr_2d):", np.size(arr_2d))

# Axis 0 → rows (down direction)
print("Axis 0 (rows):", np.size(arr_2d, axis=0))

# Axis 1 → columns (right direction)
print("Axis 1 (columns):", np.size(arr_2d, axis=1))

# =====================================================
# 3D ARRAY
# =====================================================
print("\n========== 3D ARRAY ==========")

arr_3d = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print("Array:\n", arr_3d)

# Total elements
print("np.size(arr_3d):", np.size(arr_3d))

# Axis 0 → depth (blocks)
print("Axis 0 (depth):", np.size(arr_3d, axis=0))

# Axis 1 → rows inside each block
print("Axis 1 (rows):", np.size(arr_3d, axis=1))

# Axis 2 → columns
print("Axis 2 (columns):", np.size(arr_3d, axis=2))


# =====================================================
# QUICK SUMMARY (IMPORTANT)
# =====================================================
print("\n========== SUMMARY ==========")
print("1D: axis=0 → full size")
print("2D: axis=0 → rows, axis=1 → columns")
print("3D: axis=0 → depth, axis=1 → rows, axis=2 → columns")


========== 1D ARRAY ==========
Array: [10 20 30 40 50]
np.size(arr_1d): 5
np.size(arr_1d, axis=0): 5

========== 2D ARRAY ==========
Array:
 [[1 2 3]
 [4 5 6]]
np.size(arr_2d): 6
Axis 0 (rows): 2
Axis 1 (columns): 3

========== 3D ARRAY ==========
Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
np.size(arr_3d): 12
Axis 0 (depth): 2
Axis 1 (rows): 2
Axis 2 (columns): 3

========== SUMMARY ==========
1D: axis=0 → full size
2D: axis=0 → rows, axis=1 → columns
3D: axis=0 → depth, axis=1 → rows, axis=2 → columns


## 📐 5. 1D, 2D, 3D Arrays

In [ ]:
# 1D
a1 = np.array([1,2,3,4,5])

# 2D
a2 = np.array([[1,2,3],[4,5,6]])

# 3D
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(a1.shape, a1.ndim)
print(a2.shape, a2.ndim)
print(a3.shape, a3.ndim)

## 🔥 6. Special Cases in NumPy

In [ ]:
# Scalar (0D)
scalar = np.array(42)

# Boolean array
bool_arr = np.array([True, False, True])

# Empty array
empty = np.array([])

# NaN and INF
special = np.array([1, np.nan, np.inf, -np.inf])

print(scalar, scalar.ndim)
print(bool_arr)
print(empty)
print(special)

## 🔁 7. Reshape, Identity, Transpose

In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

m = np.array([[1,2,3],[4,5,6]])
print("transpose:\n", m.T)

print("identity:\n", np.eye(3))

## 🎯 Final Output

In [ ]:
print("🚀 NumPy Notebook Part-1 Completed Successfully")