# 🚀 NumPy Random (Professional Guide Notebook)
### 👨‍💻 By Salek Masud Parvez

## 📌 Topics Covered:
- random.random() (float generation)
- random.randint() (integer generation)
- 2D & 3D data generation
- ML / AI / Game / Image use cases


In [33]:
from numpy import random
import string
from collections import Counter

## 🎲 1. random.random() Explained
👉 Generates FLOAT values between 0.0 and 1.0

### 💡 Use Cases:
- Probability / chance systems
- Game mechanics (crit hit, loot drop)
- Physics noise simulation


In [2]:
print('--- random.random() EXAMPLES ---')

print('1:', random.random())

# 30% chance event
if random.random() < 0.30:
    print('2: Success triggered')
else:
    print('2: Failed trigger')

## 🎯 2. random.randint() Explained
👉 Generates INTEGER values in range [a, b]

### 💡 Use Cases:
- OTP generation
- Dice / games
- Random IDs / scoring systems


In [3]:
print('--- random.randint() EXAMPLES ---')

print('Dice:', random.randint(1, 6))
print('OTP digit:', random.randint(0, 9))
print('Year:', random.randint(2000, 2030))
print('Score:', random.randint(50, 100))

## 🧠 3. Special Use Cases (Real World)
- Password generation
- CAPTCHA system
- Monte Carlo simulation
- Game systems


In [36]:
chars = string.ascii_letters + string.digits
password = ''.join(chars[random.randint(0, len(chars)-1)] for _ in range(10))
print('Password:', password)

captcha = ''.join(str(random.randint(0, 9)) for _ in range(6))
print('CAPTCHA:', captcha)

Password: SbXjHRoemT
CAPTCHA: 705716


## 🧱 4. 2D & 3D Data Generation (VERY IMPORTANT)
👉 Used in ML, AI, Image Processing, Games


In [38]:
# 2D matrix (students marks)
matrix_2d = random.randint(40, 101, size=(5, 3))
print('2D Marks:', matrix_2d)

# 2D image (grayscale pixels)
image_2d = random.randint(0, 256, size=(4, 4))
print('2D Image:', image_2d)

# 3D tensor (image batch)
tensor_3d = random.randint(0, 256, size=(2, 3, 3))
print('3D Tensor:', tensor_3d)

2D Marks: [[47 40 78]
 [98 61 66]
 [63 65 97]
 [94 54 91]
 [45 87 54]]
2D Image: [[ 48 107 189 155]
 [132  61  55  96]
 [219 120 221 184]
 [223 233  99 198]]
3D Tensor: [[[205 255  28]
  [105   5 199]
  [125 159  56]]

 [[ 35  50 173]
  [ 52 159  58]
  [222 151  49]]]


## 🚀 5. Advanced AI / Game Use Cases
- Game map generation
- ML dataset simulation
- Noise injection for AI training


In [39]:
game_map = random.randint(0, 3, size=(6, 6))
print('Game Map:', game_map)

X = random.randint(1, 100, size=(10, 4))
print('ML Dataset:', X)

noise = random.randint(-10, 10, size=(3, 3))
print('Noise Matrix:', noise)

Game Map: [[2 1 0 0 2 2]
 [0 1 1 1 1 1]
 [1 0 2 2 2 1]
 [1 0 2 0 2 1]
 [1 2 2 1 0 2]
 [0 2 2 1 2 2]]
ML Dataset: [[31 89 62 77]
 [27  2 47 58]
 [59 45 79 38]
 [70 36 56 48]
 [39 66 77 59]
 [66 88 34 61]
 [66 80 11 21]
 [27 87 95 55]
 [90  4  5 93]
 [73 16 94 94]]
Noise Matrix: [[ 0  6 -5]
 [ 8  4  9]
 [-7  9  5]]


## 🎉 End of Notebook
