<div style='background:linear-gradient(135deg,#0f172a,#1e293b 45%,#334155);padding:32px 24px;border-radius:18px;color:white;text-align:center;box-shadow:0 18px 40px rgba(15,23,42,0.28);'>
  <h1 style='margin:0;font-size:2.3rem;letter-spacing:0.04em;'>NumPy Practice Notebook</h1>
  <p style='margin:12px 0 0;font-size:1.05rem;opacity:0.92;'>Random numbers, ndarray operations, copying, indexing, and iteration</p>
  <p style='margin:10px 0 0;font-size:0.95rem;opacity:0.8;'>Prepared by Salek Masud Parvez</p>
</div>

In [65]:
import numpy as np
from numpy import random
import string
from collections import Counter
import math

# 🎲 PART 1: RANDOM NUMBERS IN NUMPY

In [66]:
print('random float:', random.random())
print('chance event:', random.random() < 0.5)
print('dice:', random.randint(1,6))
print('otp:', random.rand(100000,999999))

random float: 0.5017957963558364
chance event: True
dice: 2


MemoryError: Unable to allocate 745. GiB for an array with shape (100000, 999999) and data type float64

In [61]:
print('uniform [0, 1):', random.uniform())
print('uniform [10, 20):', random.uniform(10, 20))
print('range integers:', random.randint(1, 11, size=5))
print('dice roll batch:', random.randint(1, 7, size=10))

uniform [0, 1): 0.6463054967196243
uniform [10, 20): 15.495049574631473
range integers: [7 3 4 8 3]
dice roll batch: [1 4 3 2 6 5 1 4 2 2]


# 🧱 PART 2: NDARRAY BASICS (SHAPE • DTYPE • SIZE)

In [54]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print("arr1.ndim:", arr1.ndim)
print("arr2.ndim:", arr2.ndim)
print("arr3.ndim:", arr3.ndim)

print("arr1.shape:", arr1.shape)
print("arr2.shape:", arr2.shape)
print("arr3.shape:", arr3.shape)

print("arr1.dtype:", arr1.dtype)
print("arr2.dtype:", arr2.dtype)
print("arr3.dtype:", arr3.dtype)

print("arr1.size:", arr1.size)
print("arr2.size:", arr2.size)
print("arr3.size:", arr3.size)

arr1.ndim: 1
arr2.ndim: 2
arr3.ndim: 3
arr1.shape: (5,)
arr2.shape: (2, 3)
arr3.shape: (3, 2, 3)
arr1.dtype: int64
arr2.dtype: int64
arr3.dtype: int64
arr1.size: 5
arr2.size: 6
arr3.size: 18


# 🧩 PART 3: COPY VS REFERENCE

In [62]:
base_arr = np.array([10, 20, 30, 40])
reference_arr = base_arr
copied_arr = base_arr.copy()

reference_arr[0] = 999

print('original array:', base_arr)
print('copied array   :', copied_arr)
print('same object?   :', base_arr is reference_arr)
print('copy object?   :', base_arr is copied_arr)

original array: [999  20  30  40]
copied array   : [10 20 30 40]
same object?   : True
copy object?   : False


# 🔥 PART 4: ARRAY CREATION FUNCTIONS

In [55]:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.full((2,3),7))
print(np.empty((2,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1.5e-323 9.9e-324]
 [9.9e-324 1.5e-323]]


# 🔄 PART 5: DATA TYPE SYSTEM

In [56]:
print(np.array([1,2,3]).dtype)
print(np.array([1.5,2.4,3.2]).dtype)
print(np.array([1,2,3.2,'hello']).dtype)

int64
float64
<U32


# 📊 PART 6: ADVANCED INDEXING & ITERATION

In [63]:
advanced = np.array([[10,20,30],[40,50,60],[70,80,90]])

print('selected diagonal-like values:', advanced[[0,1,2],[0,1,2]])
print('picked rows:', advanced[[0,2]])
print('values above 45:', advanced[advanced > 45])

print('iterating row by row:')
for row in advanced:
    print(row)

print('iterating element by element:')
for v in advanced.flat:
    print(v, end=' ')
print()

selected diagonal-like values: [10 50 90]
picked rows: [[10 20 30]
 [70 80 90]]
values above 45: [50 60 70 80 90]
iterating row by row:
[10 20 30]
[40 50 60]
[70 80 90]
iterating element by element:
10 20 30 40 50 60 70 80 90 


# 🎉 FINAL: YOU ARE NOW NUMPY MASTER 🚀

In [10]:
print('YOU ARE NOW NUMPY MASTER 🚀')